name: Build and Upload Artifacts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
        
      - name: Build with Maven
        run: mvn clean install

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-build-artifact
          path: target/*.jar
